banknote:
  name: "&bBank Note &e(Right-Click)"
  lore:
    - "&d&lValue: $%value%"
    - "&d&lSigner: %owner%"

  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  item: PAPER

  min: 100 # minimum value of the banknote
  max: 10000 # maximum value of the banknote

  # sounds that will be played when the note is used
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sounds:
    withdraw:
      sound: BLOCK_NOTE_BLOCK_PLING
      enabled: true
    redeem:
      sound: ENTITY_PLAYER_LEVELUP
      enabled: true

expbottle:
  name: "&bExp Bottle &e&l(Right-Click)"
  lore:
    - "&d&lValue: %value%EXP"

  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  item: EXPERIENCE_BOTTLE

  min: 100 # minimum value of the banknote
  max: 10000 # maximum value of the exp

  # sounds that will be played when the bottle is used
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sounds:
    withdraw:
      sound: BLOCK_NOTE_BLOCK_PLING
      enabled: true
    redeem:
      sound: ENTITY_PLAYER_LEVELUP
      enabled: true

crafting: false # can items be used on crafting table
drop: false # can items be dropped
villager-trade: false # can items be used on villager trades

