economy-plugin: vault # Default is vault, Supported: vault, playerpoints. Can choose more than one.

banknote:
  name: "&bBank Note &e(Right-Click)"
  lore:
    - "&b&lValue: &7$%value%"
    - "&b&lSigner: &7%owner%"
    - " "
    - "&e&l(Shift-Right-Click) &7to bulk-open"

  min: 100 # minimum value of the banknote
  max: 10000 # maximum value of the banknote
  # List of all available materials.
  # if the material is not right paper will be default.
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  item: PAPER



  # List of all the available sounds.

  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sounds:
    withdraw:
      sound: BLOCK_NOTE_BLOCK_PLING
      enabled: true
    redeem:
      sound: ENTITY_PLAYER_LEVELUP
      enabled: true

expbottle:
  name: "&bExp Bottle &e&l(Right-Click)"
  lore:
    - "&b&lValue: &7%exp%EXP"
    - " "
    - "&e&l(Shift-Right-Click) &7to bulk-open"


  min: 100 # minimum value of the exp bottle
  max: 10000 # maximum value of the exp bottle

  # List of all available materials.
  # if material is not right experience bottle will be default
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  item: EXPERIENCE_BOTTLE


  # List of all the available sounds.
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sounds:
    withdraw:
      sound: BLOCK_NOTE_BLOCK_PLING
      enabled: true
    redeem:
      sound: ENTITY_PLAYER_LEVELUP
      enabled: true

crafting: false # can items be used on crafting table
drop: false # can items be dropped
villager-trade: false # can items be used on villager trades

