name: Withdrawer
version: '${version}'
main: me.imlukas.withdrawer.Withdrawer
api-version: 1.16
softdepend: [ Essentials, PlayerPoints, Vault, PlaceholderAPI ]
authors: [ imlukas ]
description: Withdraw money, exp and hp from items!
