name: Withdrawer
version: '${version}'
main: me.imlukas.withdrawer.Withdrawer
api-version: 1.16
softdepend: [ Essentials, PlayerPoints, Vault ]
authors: [ imlukas ]
description: Withdraw money and exp trough items!
commands:
  withdrawmoney:
    usage: </command>
    description: "Withdraw money"
    aliases:
      - wdmoney
  withdrawxp:
    usage: </command>
    description: "Withdraw xp"
    aliases:
      - wdxp
  withdrawhp:
    usage: </command>
    description: "Withdraw hp"
    aliases:
      - wdhp
  withdrawer:
    usage: </command>
    description: "Withdrawer commands"
    aliases:
      - wd